apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-comments-api

spec:
  selector:
    matchLabels:
      app: ratemybeer-comments-api

  replicas: {{ .Values.replicaCount }} 

  template:
    metadata:
      labels:
        app: ratemybeer-comments-api

    spec:
      containers:
        - name: ratemybeer-comments-api
          image: "thinkexception.azurecr.io/commentsapi:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "600m"
            requests:
              memory: "128Mi"
              cpu: "100m"

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
         
          ports:
            - containerPort: 8080
