version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  lab-ratemybeer-checkins:
    container_name: lab-ratemybeer-checkins
    image: labratemybeercheckins
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Checkins/Dockerfile
    restart: on-failure:10
    depends_on:
     - rabbitmq

  lab-ratemybeer-frontend-api:
    container_name: lab-ratemybeer-frontend-api
    image: labratemybeerfrontendapi
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Frontend.Api/Dockerfile
    restart: on-failure:10
    depends_on:
      - rabbitmq
      - lab-ratemybeer-checkins

  lab-ratemybeer-frontend:
    container_name: lab-ratemybeer-frontend
    image: labratemybeerfrontend
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Frontend/Dockerfile
    depends_on:
      - lab-ratemybeer-frontend-api