version: '3.4'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest   
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./Lab.RateMyBeer.RabbitMq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./Lab.RateMyBeer.RabbitMq/data/:/var/lib/rabbitmq/"
      #- "./Lab.RateMyBeer.RabbitMq/log/:/var/log/rabbitmq"
      #- "./Lab.RateMyBeer.RabbitMq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"

  sqlserver:
    container_name: "sqlserver"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=1stChangeIt!
    ports:
    - '1533:1433'
    volumes:
    - ./Lab.RateMyBeer.SQLServer/Volumes:/var/opt/mssql/data

  lab.ratemybeer.frontend.api:
    container_name: "lab.ratemybeer.frontend.api"
    image: ${DOCKER_REGISTRY-}labratemybeerfrontendapi
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Frontend.Api/Dockerfile
    restart: on-failure:10
    depends_on:
      - rabbitmq

  lab.ratemybeer.frontend:
    container_name: "lab.ratemybeer.frontend"
    image: ${DOCKER_REGISTRY-}labratemybeerfrontend
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Frontend/Dockerfile
    depends_on:
      - lab.ratemybeer.frontend.api

  lab.ratemybeer.checkins:
    container_name: "lab.ratemybeer.checkins"
    image: ${DOCKER_REGISTRY-}labratemybeercheckins
    build:
      context: .
      dockerfile: Lab.RateMyBeer.Checkins/Dockerfile
    restart: on-failure:10
    depends_on:
      - rabbitmq

  # Seperate Service for NServicBus endpoint

  

