apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-06-21T09:57:24Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"name":"mssql","namespace":"ratemybeer","resourceVersion":"7023","selfLink":"/api/v1/namespaces/ratemybeer/services/mssql","uid":"ce9a5cce-1e57-4d26-8734-8cd40065a14d"},"spec":{"clusterIP":"10.0.86.71","externalTrafficPolicy":"Cluster","ports":[{"nodePort":31141,"port":1433,"protocol":"TCP","targetPort":1433}],"selector":{"app":"mssqlboo"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"20.93.184.197"}]}}}
  creationTimestamp: "2021-06-21T09:57:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: mssql
  namespace: ratemybeer
  resourceVersion: "10096"
  selfLink: /api/v1/namespaces/ratemybeer/services/mssql
  uid: ce9a5cce-1e57-4d26-8734-8cd40065a14d
spec:
  clusterIP: 10.0.86.71
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31141
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: mssql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 20.93.184.197
