apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-ratings-api

spec:
  selector:
    matchLabels:
      app: ratemybeer-ratings-api

  replicas: 3

  template:
    metadata:
      labels:
        app: ratemybeer-ratings-api

    spec:
      containers:
        - name: ratemybeer-ratings-api
          image: thinkexception.azurecr.io/ratingsapi:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "600m"
            requests:
              memory: "128Mi"
              cpu: "100m"

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: ConnectionStrings__RatingsDbConnectionString
              valueFrom:
                secretKeyRef:
                  name: connectionstrings
                  key: DatabaseConnectionString

            - name: Dependencies__NServiceBus__TransportConnectionString
              valueFrom:
                secretKeyRef:
                  name: connectionstrings
                  key: NServiceBusTransportConnectionString
         
          ports:
            - containerPort: 8080
