apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-checkins

spec:
  replicas: 1

  template:

    spec:
      containers:
        - name: ratemybeer-checkins

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          
