apiVersion: v1
kind: Service
metadata:
  name: lab-ratemybeer-checkins-api
spec:
  selector:
    app: lab-ratemybeer-checkins-api

  ports:
    - name: http
      port: 80
      targetPort: 80

    - name: https
      port: 443
      targetPort: 443

  type: ClusterIP
