apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-frontend-api

spec:
  replicas: 3

  template:

    spec:
      containers:
        - name: ratemybeer-frontend-api

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development


