apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-ratemybeer-frontend
spec:
  selector:
    matchLabels:
      app: lab-ratemybeer-frontend
  template:
    metadata:
      labels:
        app: lab-ratemybeer-frontend
    spec:
      containers:
      - name: lab-ratemybeer-frontend
        image: ratemybeercontainer.azurecr.io/frontend:dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: BLAZOR_ENVIRONMENT
          value: Kubernetes # Use when not having cert manager ready
          # value: KubernetesHttps # Must be used after cert-manager is installed and frontend is served via https
        ports:
        - containerPort: 80
