apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab-ratemybeer-frontend
  labels:
    name: lab-ratemybeer-frontend
  
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/issuer: "letsencrypt-prod-http-issuer" # needed for tls

spec:
  # needed for tls
  #tls:
  #- hosts:
  #  - ratemybeer.westeurope.cloudapp.azure.com
  #  secretName: lab-ratemybeer-frontend-ssl

  rules:
  - host: ratemybeer.westeurope.cloudapp.azure.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: lab-ratemybeer-frontend
            port: 
              number: 80