apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-ratemybeer-checkins-api
spec:
  selector:
    matchLabels:
      app: lab-ratemybeer-checkins-api
  template:
    metadata:
      labels:
        app: lab-ratemybeer-checkins-api
    spec:
      containers:
      - name: lab-ratemybeer-checkins-api
        image: ratemybeercontainers.azurecr.io/checkinsapi:dev
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Dependencies__NServiceBus__TransportConnectionString
          value: host=rabbitmq;username=guest;password=guest
        - name: ConnectionStrings__CheckinsDbConnectionString
          value: Server=mssql;Database=CheckinsDb;User=sa;Password=1stChangeIt!;MultipleActiveResultSets=true
        ports:
        - containerPort: 80
