apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-frontend-api

spec:
  selector:
    matchLabels:
      app: ratemybeer-frontend-api

  replicas: 3

  template:
    metadata:
      labels:
        app: ratemybeer-frontend-api

    spec:
      containers:
        - name: ratemybeer-frontend-api
          image: thinkexception.azurecr.io/frontendapi:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "600m"
            requests:
              memory: "128Mi"
              cpu: "100m"

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: Dependencies__APIs__CheckinsApiBaseUrl
              value: http://ratemybeer-checkins-api

            - name: Dependencies__APIs__CommentsApiBaseUrl
              value: http://ratemybeer-comments-api
              
            - name: Dependencies__APIs__RatingsApiBaseUrl 
              value: http://ratemybeer-ratings-api
            
            - name: Dependencies__NServiceBus__TransportConnectionString
              valueFrom:
                secretKeyRef:
                  name: connectionstrings
                  key: NServiceBusTransportConnectionString
                  
          ports:
            - containerPort: 8080
