apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemybeer-ratings

spec:
  replicas: 1

  template:

    spec:
      containers:
        - name: ratemybeer-ratings

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
          
