# kubectl create secret generic mssql-sapassword --from-literal=SA_PASSWORD="1stChangeIt!"
# WSL: echo -n 1stChangeIt | base64

apiVersion: v1
kind: Secret
metadata:
  name: mssql-sapassword

type: Opaque

data:
  SA_PASSWORD: MXN0Q2hhbmdlSXQh
